//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.07.28 at 01:44:19 AM YEKT 
//


package ru.esb.xmlns.ext.contractservice;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the ru.esb.xmlns.ext.contractservice package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: ru.esb.xmlns.ext.contractservice
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link CreateNewContractRequest }
     * 
     */
    public CreateNewContractRequest createCreateNewContractRequest() {
        return new CreateNewContractRequest();
    }

    /**
     * Create an instance of {@link CreateNewContractRequest.ContractualParties }
     * 
     */
    public CreateNewContractRequest.ContractualParties createCreateNewContractRequestContractualParties() {
        return new CreateNewContractRequest.ContractualParties();
    }

    /**
     * Create an instance of {@link CreateNewContractResponse }
     * 
     */
    public CreateNewContractResponse createCreateNewContractResponse() {
        return new CreateNewContractResponse();
    }

    /**
     * Create an instance of {@link CreateNewContractRequest.ContractualParties.ContractualParty }
     * 
     */
    public CreateNewContractRequest.ContractualParties.ContractualParty createCreateNewContractRequestContractualPartiesContractualParty() {
        return new CreateNewContractRequest.ContractualParties.ContractualParty();
    }

}
