//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.07.28 at 01:44:19 AM YEKT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://xmlns.esb.ru/ext/ContractService/", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package ru.esb.xmlns.ext.contractservice;
